from __future__ import annotations

from typing import Any

Tool = dict[str, Any]

TOOLS: list[Tool] = [
    {
        "slug": "profit-margin-calculator",
        "name": "Profit Margin Calculator",
        "short_name": "Profit Margin",
        "summary": "Calculate gross profit, profit margin, and markup from cost and selling price.",
        "category": "Sales",
        "icon": "chart-up",
        "formula": "profit_margin",
        "inputs": [
            {
                "id": "cost",
                "label": "Cost price",
                "value": 100,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "selling",
                "label": "Selling price",
                "value": 150,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
        ],
        "results": [
            {"key": "profit", "label": "Gross profit", "format": "currency"},
            {"key": "margin", "label": "Profit margin", "format": "percent"},
            {"key": "markup", "label": "Markup", "format": "percent"},
        ],
        "guide": "Margin measures profit against revenue. Markup measures profit against cost.",
        "formula_text": "Margin = (Selling price − Cost) ÷ Selling price × 100",
    },
    {
        "slug": "markup-calculator",
        "name": "Markup Calculator",
        "short_name": "Markup",
        "summary": "Turn a target markup into a recommended selling price and projected margin.",
        "category": "Sales",
        "icon": "tag",
        "formula": "markup",
        "inputs": [
            {
                "id": "cost",
                "label": "Cost price",
                "value": 100,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "markup",
                "label": "Markup percentage",
                "value": 30,
                "min": 0,
                "step": 0.01,
                "kind": "percent",
            },
        ],
        "results": [
            {"key": "selling", "label": "Selling price", "format": "currency"},
            {"key": "profit", "label": "Profit", "format": "currency"},
            {"key": "margin", "label": "Resulting margin", "format": "percent"},
        ],
        "guide": "Use markup when setting a selling price from a known product or service cost.",
        "formula_text": "Selling price = Cost × (1 + Markup ÷ 100)",
    },
    {
        "slug": "discount-calculator",
        "name": "Discount Calculator",
        "short_name": "Discount",
        "summary": "Find the final price and customer savings after a percentage discount.",
        "category": "Sales",
        "icon": "percent",
        "formula": "discount",
        "inputs": [
            {
                "id": "price",
                "label": "Original price",
                "value": 100,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "discount",
                "label": "Discount percentage",
                "value": 15,
                "min": 0,
                "max": 100,
                "step": 0.01,
                "kind": "percent",
            },
        ],
        "results": [
            {"key": "final", "label": "Final price", "format": "currency"},
            {"key": "savings", "label": "Customer saves", "format": "currency"},
            {"key": "effective", "label": "Effective discount", "format": "percent"},
        ],
        "guide": "Useful for promotions, quotations, and price negotiations.",
        "formula_text": "Final price = Original price × (1 − Discount ÷ 100)",
    },
    {
        "slug": "sales-commission-calculator",
        "name": "Sales Commission Calculator",
        "short_name": "Commission",
        "summary": "Calculate sales commission, total payout, and revenue after commission.",
        "category": "Team",
        "icon": "users",
        "formula": "commission",
        "inputs": [
            {
                "id": "sales",
                "label": "Total sales",
                "value": 10000,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "rate",
                "label": "Commission rate",
                "value": 5,
                "min": 0,
                "step": 0.01,
                "kind": "percent",
            },
            {
                "id": "base",
                "label": "Fixed payout",
                "value": 0,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
        ],
        "results": [
            {"key": "commission", "label": "Commission", "format": "currency"},
            {"key": "payout", "label": "Total payout", "format": "currency"},
            {"key": "net", "label": "Revenue after commission", "format": "currency"},
        ],
        "guide": "Works for salespeople, agents, affiliates, and performance-based compensation.",
        "formula_text": "Commission = Sales × Commission rate ÷ 100",
    },
    {
        "slug": "vat-calculator",
        "name": "VAT Calculator",
        "short_name": "VAT",
        "summary": "Add VAT to a net amount or extract VAT from a VAT-inclusive amount.",
        "category": "Finance",
        "icon": "receipt-tax",
        "formula": "vat",
        "inputs": [
            {
                "id": "amount",
                "label": "Amount",
                "value": 1000,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "rate",
                "label": "VAT rate",
                "value": 15,
                "min": 0,
                "step": 0.01,
                "kind": "percent",
            },
        ],
        "results": [
            {"key": "vat", "label": "VAT to add", "format": "currency"},
            {"key": "gross", "label": "Total including VAT", "format": "currency"},
            {"key": "included", "label": "VAT inside inclusive amount", "format": "currency"},
        ],
        "guide": "This is a general calculation aid, not jurisdiction-specific tax advice.",
        "formula_text": "VAT = Net amount × VAT rate ÷ 100",
    },
    {
        "slug": "break-even-calculator",
        "name": "Break-even Calculator",
        "short_name": "Break-even",
        "summary": "Estimate the sales volume and revenue needed to cover all costs.",
        "category": "Planning",
        "icon": "target",
        "formula": "break_even",
        "inputs": [
            {
                "id": "fixed",
                "label": "Fixed costs",
                "value": 5000,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "price",
                "label": "Selling price per unit",
                "value": 50,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "variable",
                "label": "Variable cost per unit",
                "value": 30,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
        ],
        "results": [
            {"key": "units", "label": "Break-even units", "format": "integer"},
            {"key": "revenue", "label": "Break-even revenue", "format": "currency"},
            {"key": "contribution", "label": "Contribution per unit", "format": "currency"},
        ],
        "guide": "Contribution is the amount each unit contributes toward fixed costs and profit.",
        "formula_text": "Break-even units = Fixed costs ÷ (Price − Variable cost)",
    },
    {
        "slug": "overtime-pay-calculator",
        "name": "Overtime Pay Calculator",
        "short_name": "Overtime Pay",
        "summary": "Calculate regular pay, overtime pay, and total gross pay.",
        "category": "Team",
        "icon": "clock",
        "formula": "overtime",
        "inputs": [
            {
                "id": "hourly",
                "label": "Hourly rate",
                "value": 10,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "regular_hours",
                "label": "Regular hours",
                "value": 40,
                "min": 0,
                "step": 0.25,
                "kind": "hours",
            },
            {
                "id": "overtime_hours",
                "label": "Overtime hours",
                "value": 5,
                "min": 0,
                "step": 0.25,
                "kind": "hours",
            },
            {
                "id": "multiplier",
                "label": "Overtime multiplier",
                "value": 1.5,
                "min": 0,
                "step": 0.1,
                "kind": "number",
            },
        ],
        "results": [
            {"key": "regular", "label": "Regular pay", "format": "currency"},
            {"key": "overtime", "label": "Overtime pay", "format": "currency"},
            {"key": "total", "label": "Total gross pay", "format": "currency"},
        ],
        "guide": "Employment rules vary. Verify the legally required multiplier in your location.",
        "formula_text": "Overtime pay = Hourly rate × Overtime hours × Multiplier",
    },
    {
        "slug": "roi-calculator",
        "name": "ROI Calculator",
        "short_name": "ROI",
        "summary": "Measure return on investment, net profit, and investment multiple.",
        "category": "Planning",
        "icon": "trending-up",
        "formula": "roi",
        "inputs": [
            {
                "id": "investment",
                "label": "Initial investment",
                "value": 5000,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "return_value",
                "label": "Final value or return",
                "value": 6500,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
        ],
        "results": [
            {"key": "profit", "label": "Net profit", "format": "currency"},
            {"key": "roi", "label": "ROI", "format": "percent"},
            {"key": "multiple", "label": "Investment multiple", "format": "multiple"},
        ],
        "guide": "ROI helps compare opportunities, but it does not account for time or risk by itself.",
        "formula_text": "ROI = (Final value − Investment) ÷ Investment × 100",
    },
    {
        "slug": "cash-runway-calculator",
        "name": "Cash Runway Calculator",
        "short_name": "Cash Runway",
        "summary": "Estimate how many months your business can operate at its current burn rate.",
        "category": "Planning",
        "icon": "calendar",
        "formula": "cash_runway",
        "inputs": [
            {
                "id": "cash",
                "label": "Available cash",
                "value": 50000,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "monthly_burn",
                "label": "Monthly net burn",
                "value": 8000,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
        ],
        "results": [
            {"key": "months", "label": "Cash runway", "format": "months"},
            {"key": "days", "label": "Approximate days", "format": "integer"},
            {"key": "six_month_need", "label": "Cash needed for 6 months", "format": "currency"},
        ],
        "guide": "Use net burn after recurring revenue, not total expenses, for a realistic runway.",
        "formula_text": "Runway = Available cash ÷ Monthly net burn",
    },
    {
        "slug": "reorder-point-calculator",
        "name": "Inventory Reorder Point Calculator",
        "short_name": "Reorder Point",
        "summary": "Calculate when to reorder stock using demand, lead time, and safety stock.",
        "category": "Operations",
        "icon": "boxes",
        "formula": "reorder_point",
        "inputs": [
            {
                "id": "daily_usage",
                "label": "Average daily usage",
                "value": 12,
                "min": 0,
                "step": 0.01,
                "kind": "units",
            },
            {
                "id": "lead_days",
                "label": "Supplier lead time (days)",
                "value": 7,
                "min": 0,
                "step": 1,
                "kind": "days",
            },
            {
                "id": "safety_stock",
                "label": "Safety stock",
                "value": 25,
                "min": 0,
                "step": 0.01,
                "kind": "units",
            },
        ],
        "results": [
            {"key": "reorder", "label": "Reorder point", "format": "units"},
            {"key": "lead_demand", "label": "Expected lead-time demand", "format": "units"},
            {"key": "coverage", "label": "Safety-stock coverage", "format": "days"},
        ],
        "guide": "Reorder when available stock reaches this point, assuming steady average demand.",
        "formula_text": "Reorder point = Daily usage × Lead time + Safety stock",
    },
    {
        "slug": "unit-economics-calculator",
        "name": "Unit Economics Calculator",
        "short_name": "Unit Economics",
        "summary": "Estimate contribution margin, gross margin, and customer acquisition payback.",
        "category": "Planning",
        "icon": "layers",
        "formula": "unit_economics",
        "inputs": [
            {
                "id": "revenue",
                "label": "Revenue per customer/month",
                "value": 100,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "variable_cost",
                "label": "Variable cost per customer/month",
                "value": 35,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
            {
                "id": "cac",
                "label": "Customer acquisition cost",
                "value": 200,
                "min": 0,
                "step": 0.01,
                "kind": "money",
            },
        ],
        "results": [
            {"key": "contribution", "label": "Monthly contribution", "format": "currency"},
            {"key": "margin", "label": "Contribution margin", "format": "percent"},
            {"key": "payback", "label": "CAC payback", "format": "months"},
        ],
        "guide": "A shorter CAC payback period generally improves cash efficiency, but retention still matters.",
        "formula_text": "CAC payback = Acquisition cost ÷ Monthly contribution",
    },
]

TOOLS_BY_SLUG = {tool["slug"]: tool for tool in TOOLS}
CATEGORIES = sorted({tool["category"] for tool in TOOLS})

DOCUMENT_TYPES = {
    "invoice": {
        "name": "Invoice Generator",
        "noun": "Invoice",
        "summary": "Create a professional invoice, autosave it locally, and export it as PDF.",
        "prefix": "INV",
        "icon": "file-text",
    },
    "quotation": {
        "name": "Quotation Generator",
        "noun": "Quotation",
        "summary": "Build a clear customer quotation with pricing, terms, and validity date.",
        "prefix": "QUO",
        "icon": "clipboard",
    },
    "receipt": {
        "name": "Receipt Generator",
        "noun": "Receipt",
        "summary": "Generate a clean payment receipt for customers and your records.",
        "prefix": "REC",
        "icon": "receipt",
    },
    "purchase-order": {
        "name": "Purchase Order Generator",
        "noun": "Purchase Order",
        "summary": "Prepare a purchase order with supplier, delivery, and line-item details.",
        "prefix": "PO",
        "icon": "shopping-bag",
    },
}
