from __future__ import annotations

TOOLS = [
    {
        "slug": "profit-margin-calculator",
        "name": "Profit Margin Calculator",
        "short_name": "Profit Margin",
        "summary": "Calculate gross profit, margin percentage, and markup from cost and selling price.",
        "category": "Sales",
        "icon": "%",
        "formula": "profit_margin",
        "inputs": [
            {"id": "cost", "label": "Cost price", "value": "100", "min": "0", "step": "0.01"},
            {"id": "selling", "label": "Selling price", "value": "150", "min": "0", "step": "0.01"},
        ],
        "results": ["Gross profit", "Profit margin", "Markup"],
        "guide": "Enter the total cost and final selling price. Margin is profit as a percentage of revenue; markup is profit as a percentage of cost.",
    },
    {
        "slug": "markup-calculator",
        "name": "Markup Calculator",
        "short_name": "Markup",
        "summary": "Turn a target markup into a recommended selling price and projected profit.",
        "category": "Sales",
        "icon": "↗",
        "formula": "markup",
        "inputs": [
            {"id": "cost", "label": "Cost price", "value": "100", "min": "0", "step": "0.01"},
            {"id": "markup", "label": "Markup percentage", "value": "30", "min": "0", "step": "0.01"},
        ],
        "results": ["Selling price", "Profit", "Resulting margin"],
        "guide": "Markup adds a percentage of cost to the price. A 30% markup on 100 produces a selling price of 130.",
    },
    {
        "slug": "discount-calculator",
        "name": "Discount Calculator",
        "short_name": "Discount",
        "summary": "Find the discounted price, customer savings, and effective discount.",
        "category": "Sales",
        "icon": "−",
        "formula": "discount",
        "inputs": [
            {"id": "price", "label": "Original price", "value": "100", "min": "0", "step": "0.01"},
            {"id": "discount", "label": "Discount percentage", "value": "15", "min": "0", "max": "100", "step": "0.01"},
        ],
        "results": ["Final price", "You save", "Discount amount"],
        "guide": "Use this for promotions, quotations, and price negotiations. The result updates instantly in your browser.",
    },
    {
        "slug": "sales-commission-calculator",
        "name": "Sales Commission Calculator",
        "short_name": "Commission",
        "summary": "Calculate commission, net revenue, and total payout from sales.",
        "category": "Team",
        "icon": "◎",
        "formula": "commission",
        "inputs": [
            {"id": "sales", "label": "Total sales", "value": "10000", "min": "0", "step": "0.01"},
            {"id": "rate", "label": "Commission rate", "value": "5", "min": "0", "step": "0.01"},
            {"id": "base", "label": "Base salary or fixed payout", "value": "0", "min": "0", "step": "0.01"},
        ],
        "results": ["Commission", "Total payout", "Revenue after commission"],
        "guide": "Useful for salespeople, agents, referral partners, and performance-based compensation plans.",
    },
    {
        "slug": "vat-calculator",
        "name": "VAT Calculator",
        "short_name": "VAT",
        "summary": "Add VAT to a net price or extract VAT from a VAT-inclusive price.",
        "category": "Finance",
        "icon": "+",
        "formula": "vat",
        "inputs": [
            {"id": "amount", "label": "Amount", "value": "1000", "min": "0", "step": "0.01"},
            {"id": "rate", "label": "VAT rate", "value": "15", "min": "0", "step": "0.01"},
        ],
        "results": ["VAT amount", "Total including VAT", "Net amount if VAT-inclusive"],
        "guide": "This is a general mathematical calculator, not tax advice. Always verify the applicable VAT rules in your jurisdiction.",
    },
    {
        "slug": "break-even-calculator",
        "name": "Break-even Calculator",
        "short_name": "Break-even",
        "summary": "Estimate how many units you must sell to cover fixed and variable costs.",
        "category": "Planning",
        "icon": "=",
        "formula": "break_even",
        "inputs": [
            {"id": "fixed", "label": "Fixed costs", "value": "5000", "min": "0", "step": "0.01"},
            {"id": "price", "label": "Selling price per unit", "value": "50", "min": "0", "step": "0.01"},
            {"id": "variable", "label": "Variable cost per unit", "value": "30", "min": "0", "step": "0.01"},
        ],
        "results": ["Break-even units", "Break-even revenue", "Contribution per unit"],
        "guide": "Break-even units equal fixed costs divided by the contribution earned from each unit sold.",
    },
    {
        "slug": "loan-payment-calculator",
        "name": "Loan Payment Calculator",
        "short_name": "Loan Payment",
        "summary": "Estimate monthly payment, total repayment, and total interest.",
        "category": "Finance",
        "icon": "¤",
        "formula": "loan",
        "inputs": [
            {"id": "principal", "label": "Loan amount", "value": "10000", "min": "0", "step": "0.01"},
            {"id": "annual_rate", "label": "Annual interest rate", "value": "10", "min": "0", "step": "0.01"},
            {"id": "months", "label": "Term in months", "value": "12", "min": "1", "step": "1"},
        ],
        "results": ["Monthly payment", "Total repayment", "Total interest"],
        "guide": "This estimate assumes a fixed interest rate and equal monthly payments. Lender fees are not included.",
    },
    {
        "slug": "overtime-pay-calculator",
        "name": "Overtime Pay Calculator",
        "short_name": "Overtime Pay",
        "summary": "Calculate regular pay, overtime pay, and total gross pay.",
        "category": "Team",
        "icon": "◷",
        "formula": "overtime",
        "inputs": [
            {"id": "hourly", "label": "Hourly rate", "value": "10", "min": "0", "step": "0.01"},
            {"id": "regular_hours", "label": "Regular hours", "value": "40", "min": "0", "step": "0.25"},
            {"id": "overtime_hours", "label": "Overtime hours", "value": "5", "min": "0", "step": "0.25"},
            {"id": "multiplier", "label": "Overtime multiplier", "value": "1.5", "min": "0", "step": "0.1"},
        ],
        "results": ["Regular pay", "Overtime pay", "Total gross pay"],
        "guide": "Employment rules differ by location. Use this as a calculation aid and verify the legally required overtime rate.",
    },
]

TOOLS_BY_SLUG = {tool["slug"]: tool for tool in TOOLS}
